### ISSUE TITLE
Please support language code from cookie

### ISSUE THREAD

**Issue by hoanghiep** [codeva/hapi-i18n#11]
Hi codeva

Please support language code from cookie. My clients use browser with default language (en), but they wanna to change language to pt. I cannot change all resources in my project.

**Comment by funktionswerk** [comment]
Hi hoanghiep,

This plugin is supposed to read the language code from the path parameter. Can you change the set up of the URLs to get the language code from the request URL? Then the client can simply change the language code by modifying the URL.
