### ISSUE TITLE
support http header `Accept-Language`

### ISSUE THREAD

**Issue by jney** [codeva/hapi-i18n#4]
could the plugin support `Accept-Language` and have appropriate `Content-Language` in the response ?

ie:

```
curl -i 0.0.0.0:3333/hello -H 'Accept-Language: fr'

HTTP/1.1 200 OK
content-language: fr

salut
```

**Comment by jney** [comment]
for info:

```js
req.i18n.locale // "fr"
req.i18n.getLocale() // "en"
```

**Comment by codeva** [comment]
Did you have a look at https://github.com/ozum/hapi-locale? This plugin supports the extraction of the locale from the request header.
