### ISSUE TITLE
While translating the message i got undiefined error

### ISSUE THREAD

**Issue by sivabalan02** [codeva/hapi-i18n#9]
I used glue plugin on my application. Here is my code:

i18n.js:

```'use strict';
const register = (server, options, next) => {
server.register(
{
register: require('hapi-i18n'),
options : {locales: ["en"],directory: __dirname + "/../locales",
}
});
next();
};
register.attributes = {name: 'Internationalization'};
module.exports = register;```

en.json:
{
	"GREETING": "Welcome all",
}

In my routes i specified the i18n

```              {
		method : 'POST',
		path   : "/signup",
		config : {
			tags    : ['api'],
			description: 'Customer signup',
			/*validate: {
				options: {
					abortEarly: false,
				},
				payload: signupSchema,
			}*/
		},
		handler: function(request, response){

			request.i18n.setLocale("en");
			console.log(request.i18n.getLocale());
			console.log(request.i18n.__("GREETING"));
			return response('Signup');
		}
	}```


But i only getting undefined error on it

**Comment by funktionswerk** [comment]
Can you provide a simplified setup that produces the undefined error? Maybe as a Git repo?

**Comment by sivabalan02** [comment]
[https://github.com/sivabalan02/hapi-i18n-issue](Issue link) When in call signup api http://localhost:8080/signup its gives undefined error

**Comment by funktionswerk** [comment]
There is a syntax error in your JSON file (remove the comma): https://github.com/sivabalan02/hapi-i18n-issue/blob/master/api/locales/en.json#L2
This caused a parseError when loading the i18n module. Unfortunately, i18n fails silently without any error message. You can display the logs of i18n by settings the DEBUG environment variable:
```
export DEBUG=i18n:*
```

**Comment by sivabalan02** [comment]
Thanks funktionswerk. Now its working.
